# Generated by Django 3.1.4 on 2021-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oxygen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_name', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=10)),
                ('aval', models.CharField(max_length=6)),
                ('area', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='vaccines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchc', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('nodal_officer', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=10)),
                ('aval', models.CharField(max_length=6)),
            ],
        ),
    ]
